CREATE DATABASE db_test;

USE db_test;

CREATE TABLE IF NOT EXISTS `user` (
  id INT NOT NULL AUTO_INCREMENT,
  userName VARCHAR(50) NOT NULL,
  userPassword VARCHAR(1000) NOT NULL,
  userEmail VARCHAR(50) NOT NULL,
  userLastName VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

