CREATE DATABASE db_test;

USE db_test;

CREATE TABLE IF NOT EXISTS `user` (
  id INT NOT NULL AUTO_INCREMENT,
  userName VARCHAR(50) NOT NULL,
  userPassword VARCHAR(1000) NOT NULL,
  userEmail VARCHAR(50) NOT NULL,
  userLastName VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS planets (
idPlanet INT(6) AUTO_INCREMENT PRIMARY KEY,
idUser INT NOT NULL,
idFile INT NOT NULL,
commets VARCHAR(400),
creationTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);